packages:
  - platform
  - modules/*
  - packages/*

allowBuilds:
  esbuild: true
  tldjs: false

minimumReleaseAgeExclude:
  - '@octanejs/app-core@0.0.47'
  - '@octanejs/seo@0.0.38'
  - '@octanejs/tanstack-table@0.1.51'
  - '@octanejs/vite-plugin@0.1.51'
  - octane@0.1.51
  - '@octanejs/tanstack-store@0.0.48'
  - segment-state@0.2.1
