packages:
  - platform
  - modules/*
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@octanejs/app-core@0.0.47'
  - '@octanejs/seo@0.0.36'
  - '@octanejs/tanstack-table@0.1.48'
  - '@octanejs/vite-plugin@0.1.51'
  - octane@0.1.51
  - '@octanejs/tanstack-store@0.0.45'

patchedDependencies:
  '@octanejs/seo@0.0.36': patches/@octanejs__seo@0.0.36.patch
  '@octanejs/tanstack-store@0.0.45': patches/@octanejs__tanstack-store@0.0.45.patch
  '@octanejs/tanstack-table@0.1.48': patches/@octanejs__tanstack-table@0.1.48.patch
