packages:
  - platform
  - modules/*
  - packages/*

overrides:
  'ajv@8.20.0>fast-uri': 3.1.7
  '@ai-sdk/provider-utils@5.0.34>undici': 7.29.1

allowBuilds:
  esbuild: true
  tldjs: false

minimumReleaseAgeExclude:
  - '@octanejs/app-core@0.0.47'
  - '@octanejs/seo@0.0.38'
  - '@octanejs/tanstack-table@0.1.51'
  - '@octanejs/vite-plugin@0.1.51'
  - octane@0.1.51
  - '@octanejs/tanstack-store@0.0.48'
  - segment-state@0.2.1
