// Regenerates src/brand/mark.ts from the weave parameters below.
// Run: node packages/ui/scripts/gen-mark.mjs
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const size = 24;
const w = 3.4; // thread width
const g = 1.2; // interlace gap
const step = 8.2; // thread spacing
const ext = 6.2; // overshoot past the outer crossing
const cx = size / 2;
const xs = [cx - step / 2, cx + step / 2];
const ys = [...xs];
const lo = xs[0] - ext;
const hi = xs[1] + ext;
const cut = w / 2 + g;
const f = (n) => Number(n.toFixed(2));
const over = (i, j) => ((i + j) % 2 === 1 ? 'warp' : 'weft');

function strand(id, along, fixed, cuts, vertical) {
	const shapes = [];
	shapes.push({
		id: id + 'c0',
		type: 'circle',
		cx: vertical ? fixed : lo + w / 2,
		cy: vertical ? lo + w / 2 : fixed,
		r: w / 2,
	});
	let start = lo + w / 2;
	let rect = 0;
	for (const c of cuts) {
		shapes.push(segment(id + 'r' + rect++, fixed, start, c - cut, vertical));
		start = c + cut;
	}
	shapes.push(segment(id + 'r' + rect, fixed, start, hi - w / 2, vertical));
	shapes.push({
		id: id + 'c1',
		type: 'circle',
		cx: vertical ? fixed : hi - w / 2,
		cy: vertical ? hi - w / 2 : fixed,
		r: w / 2,
	});
	return shapes;
}

function segment(id, fixed, from, to, vertical) {
	return vertical
		? {
				id,
				type: 'rect',
				x: f(fixed - w / 2),
				y: f(from),
				width: w,
				height: f(to - from),
			}
		: {
				id,
				type: 'rect',
				x: f(from),
				y: f(fixed - w / 2),
				width: f(to - from),
				height: w,
			};
}

const warp = xs.flatMap((x, i) =>
	strand(
		'w' + i,
		ys,
		x,
		ys.filter((_, j) => over(i, j) === 'weft'),
		true,
	),
);
const weft = ys.flatMap((y, j) =>
	strand(
		'f' + j,
		xs,
		y,
		xs.filter((_, i) => over(i, j) === 'warp'),
		false,
	),
);

const clean = (shapes) =>
	shapes.map((s) =>
		s.type === 'circle' ? { ...s, cx: f(s.cx), cy: f(s.cy), r: f(s.r) } : s,
	);

const render = (shapes) =>
	shapes
		.map((s) =>
			s.type === 'rect'
				? `\t{ id: '${s.id}', type: 'rect', x: ${s.x}, y: ${s.y}, width: ${s.width}, height: ${s.height} },`
				: `\t{ id: '${s.id}', type: 'circle', cx: ${s.cx}, cy: ${s.cy}, r: ${s.r} },`,
		)
		.join('\n');

const out = `/* Generated by scripts/gen-mark.mjs. Do not edit by hand.
   Plain 2x2 weave on a 24-unit grid: thread ${w}, interlace gap ${g},
   spacing ${step}, overshoot ${ext}, round thread ends. */

export const MARK_VIEWBOX = '0 0 ${size} ${size}';

export type MarkShape =
	| {
			readonly id: string;
			readonly type: 'rect';
			readonly x: number;
			readonly y: number;
			readonly width: number;
			readonly height: number;
	  }
	| {
			readonly id: string;
			readonly type: 'circle';
			readonly cx: number;
			readonly cy: number;
			readonly r: number;
	  };

export const MARK_WARP: readonly MarkShape[] = [
${render(clean(warp))}
];

export const MARK_WEFT: readonly MarkShape[] = [
${render(clean(weft))}
];
`;

const target = resolve(import.meta.dirname, '../src/brand/mark.ts');
writeFileSync(target, out);
console.log('wrote', target);
