// Regenerates src/brand/mark.ts from the bar parameters below.
// Run: node packages/ui/scripts/gen-mark.mjs
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const size = 24;
const h = 5; // bar height
const gap = 2; // space between bars
const top = 3; // first bar's top edge
const right = 22; // every bar ends here
const widths = [20, 14, 8]; // top to bottom; the last bar is the accent
const f = (n) => Number(n.toFixed(2));

/* A bar is a rect plus a circle at each end, so the shape type stays the
   one the public API already exports. */
function bar(id, y, width) {
	const r = h / 2;
	const x = right - width;
	return [
		{ id: id + 'c0', type: 'circle', cx: f(x + r), cy: f(y + r), r },
		{
			id: id + 'r',
			type: 'rect',
			x: f(x + r),
			y: f(y),
			width: f(width - h),
			height: h,
		},
		{ id: id + 'c1', type: 'circle', cx: f(right - r), cy: f(y + r), r },
	];
}

const bars = widths.map((width, index) =>
	bar('b' + index, top + index * (h + gap), width),
);
const warp = bars.slice(0, -1).flat();
const weft = bars.at(-1);

const render = (shapes) =>
	shapes
		.map((s) =>
			s.type === 'rect'
				? `\t{ id: '${s.id}', type: 'rect', x: ${s.x}, y: ${s.y}, width: ${s.width}, height: ${s.height} },`
				: `\t{ id: '${s.id}', type: 'circle', cx: ${s.cx}, cy: ${s.cy}, r: ${s.r} },`,
		)
		.join('\n');

const out = `/* Generated by scripts/gen-mark.mjs. Do not edit by hand.
   Three right-aligned bars on a 24-unit grid, ${widths.join(', ')} wide,
   ${h} high, ${gap} apart, round ends. The warp is the two ink bars and the
   weft is the short accent bar at the bottom. */

export const MARK_VIEWBOX = '0 0 ${size} ${size}';

export type MarkShape =
	| {
			readonly id: string;
			readonly type: 'rect';
			readonly x: number;
			readonly y: number;
			readonly width: number;
			readonly height: number;
	  }
	| {
			readonly id: string;
			readonly type: 'circle';
			readonly cx: number;
			readonly cy: number;
			readonly r: number;
	  };

export const MARK_WARP: readonly MarkShape[] = [
${render(warp)}
];

export const MARK_WEFT: readonly MarkShape[] = [
${render(weft)}
];
`;

const target = resolve(import.meta.dirname, '../src/brand/mark.ts');
writeFileSync(target, out);
console.log('wrote', target);
