import {
	ACTIONS_FOLDED_WIDTH,
	TABLE_STEP,
	TABLE_STEP_MAX,
	TABLE_STEP_MIN,
} from './table-layout.ts';

/** The text of `styles/table-steps.css`: one container query per step. */
export function tableStepsCss(): string {
	const blocks = [
		`/* Generated by packages/ui/scripts/gen-table-steps.mjs from table-layout.ts.
   A column's col, header and cells carry the step class it hides at, the
   expand button and the details carry the step they appear at, and a table
   carries the step its actions fold at. */`,
	];
	for (let step = TABLE_STEP_MIN; step <= TABLE_STEP_MAX; step += TABLE_STEP) {
		blocks.push(`@container (width < ${step}px) {
	.ui-table .ui-table__hide-${step} {
		display: none;
	}

	.ui-table .ui-table__reveal-${step} {
		display: grid;
	}

	.ui-table--fold-${step} {
		--ui-table-buttons: none;
		--ui-table-more: inline-flex;
		--ui-table-actions-fold: ${ACTIONS_FOLDED_WIDTH}px;
	}
}`);
	}
	return blocks.join('\n\n') + '\n';
}
