import {
	ACTIONS_FOLDED_WIDTH,
	TABLE_STEP,
	TABLE_STEP_MAX,
	TABLE_STEP_MIN,
} from './table-layout.ts';

/** The text of `styles/table-steps.css`: one container query per step. */
export function tableStepsCss(): string {
	const blocks = [
		`/* Generated by packages/ui/scripts/gen-table-steps.mjs from table-layout.ts.
   A table carries the step class for each width it hides or folds at; below
   that container width the custom properties switch the columns, the details
   and the actions over. */`,
	];
	for (let step = TABLE_STEP_MIN; step <= TABLE_STEP_MAX; step += TABLE_STEP) {
		blocks.push(`@container (width < ${step}px) {
	.ui-table--p3-${step} {
		--ui-table-p3: none;
		--ui-table-p3-detail: grid;
	}

	.ui-table--p2-${step} {
		--ui-table-p2: none;
		--ui-table-p2-detail: grid;
	}

	.ui-table--fold-${step} {
		--ui-table-buttons: none;
		--ui-table-more: inline-flex;
		--ui-table-actions-fold: ${ACTIONS_FOLDED_WIDTH}px;
	}
}`);
	}
	return blocks.join('\n\n') + '\n';
}
