apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octane-erp-auth
  labels:
    app.kubernetes.io/name: octane-erp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
