apiVersion: v1
kind: Service
metadata:
  name: flowdular
  labels:
    app.kubernetes.io/name: flowdular
spec:
  selector:
    app.kubernetes.io/name: flowdular
  ports:
    - name: http
      port: 80
      targetPort: http
