apiVersion: v1
kind: Service
metadata:
  name: octane-erp
  labels:
    app.kubernetes.io/name: octane-erp
spec:
  selector:
    app.kubernetes.io/name: octane-erp
  ports:
    - name: http
      port: 80
      targetPort: http
