apiVersion: v1
kind: Service
metadata:
  name: coreloom
  labels:
    app.kubernetes.io/name: coreloom
spec:
  selector:
    app.kubernetes.io/name: coreloom
  ports:
    - name: http
      port: 80
      targetPort: http
