/* Generated by scripts/gen-mark.mjs. Do not edit by hand.
   Three right-aligned bars on a 24-unit grid, 20, 14, 8 wide,
   5 high, 2 apart, round ends. The warp is the two ink bars and the
   weft is the short accent bar at the bottom. */

export const MARK_VIEWBOX = '0 0 24 24';

export type MarkShape =
	| {
			readonly id: string;
			readonly type: 'rect';
			readonly x: number;
			readonly y: number;
			readonly width: number;
			readonly height: number;
	  }
	| {
			readonly id: string;
			readonly type: 'circle';
			readonly cx: number;
			readonly cy: number;
			readonly r: number;
	  };

export const MARK_WARP: readonly MarkShape[] = [
	{ id: 'b0c0', type: 'circle', cx: 4.5, cy: 5.5, r: 2.5 },
	{ id: 'b0r', type: 'rect', x: 4.5, y: 3, width: 15, height: 5 },
	{ id: 'b0c1', type: 'circle', cx: 19.5, cy: 5.5, r: 2.5 },
	{ id: 'b1c0', type: 'circle', cx: 10.5, cy: 12.5, r: 2.5 },
	{ id: 'b1r', type: 'rect', x: 10.5, y: 10, width: 9, height: 5 },
	{ id: 'b1c1', type: 'circle', cx: 19.5, cy: 12.5, r: 2.5 },
];

export const MARK_WEFT: readonly MarkShape[] = [
	{ id: 'b2c0', type: 'circle', cx: 16.5, cy: 19.5, r: 2.5 },
	{ id: 'b2r', type: 'rect', x: 16.5, y: 17, width: 3, height: 5 },
	{ id: 'b2c1', type: 'circle', cx: 19.5, cy: 19.5, r: 2.5 },
];
