/* Generated by scripts/gen-mark.mjs. Do not edit by hand.
   Plain 2x2 weave on a 24-unit grid: thread 3.4, interlace gap 1.2,
   spacing 8.2, overshoot 6.2, round thread ends. */

export const MARK_VIEWBOX = '0 0 24 24';

export type MarkShape =
	| {
			readonly id: string;
			readonly type: 'rect';
			readonly x: number;
			readonly y: number;
			readonly width: number;
			readonly height: number;
	  }
	| {
			readonly id: string;
			readonly type: 'circle';
			readonly cx: number;
			readonly cy: number;
			readonly r: number;
	  };

export const MARK_WARP: readonly MarkShape[] = [
	{ id: 'w0c0', type: 'circle', cx: 7.9, cy: 3.4, r: 1.7 },
	{ id: 'w0r0', type: 'rect', x: 6.2, y: 3.4, width: 3.4, height: 1.6 },
	{ id: 'w0r1', type: 'rect', x: 6.2, y: 10.8, width: 3.4, height: 9.8 },
	{ id: 'w0c1', type: 'circle', cx: 7.9, cy: 20.6, r: 1.7 },
	{ id: 'w1c0', type: 'circle', cx: 16.1, cy: 3.4, r: 1.7 },
	{ id: 'w1r0', type: 'rect', x: 14.4, y: 3.4, width: 3.4, height: 9.8 },
	{ id: 'w1r1', type: 'rect', x: 14.4, y: 19, width: 3.4, height: 1.6 },
	{ id: 'w1c1', type: 'circle', cx: 16.1, cy: 20.6, r: 1.7 },
];

export const MARK_WEFT: readonly MarkShape[] = [
	{ id: 'f0c0', type: 'circle', cx: 3.4, cy: 7.9, r: 1.7 },
	{ id: 'f0r0', type: 'rect', x: 3.4, y: 6.2, width: 9.8, height: 3.4 },
	{ id: 'f0r1', type: 'rect', x: 19, y: 6.2, width: 1.6, height: 3.4 },
	{ id: 'f0c1', type: 'circle', cx: 20.6, cy: 7.9, r: 1.7 },
	{ id: 'f1c0', type: 'circle', cx: 3.4, cy: 16.1, r: 1.7 },
	{ id: 'f1r0', type: 'rect', x: 3.4, y: 14.4, width: 1.6, height: 3.4 },
	{ id: 'f1r1', type: 'rect', x: 10.8, y: 14.4, width: 9.8, height: 3.4 },
	{ id: 'f1c1', type: 'circle', cx: 20.6, cy: 16.1, r: 1.7 },
];
