import { spawnSync } from 'node:child_process';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { ModuleManifest } from '@coreloom/contracts';
import { findNamedFiles } from './validation.ts';
import type { Workspace } from './workspace.ts';

export interface PlatformModuleDescriptor {
	readonly id: string;
	readonly package: string;
	readonly server: boolean;
	readonly client: boolean;
}

interface PlatformManifest extends ModuleManifest {
	readonly platform?: {
		readonly server?: boolean;
		readonly client?: boolean;
	};
}

export interface SyncedFile {
	readonly path: string;
	readonly changed: boolean;
}

export interface SyncReport {
	readonly modules: readonly string[];
	readonly files: readonly SyncedFile[];
	readonly applied: boolean;
}

export interface EnableReport extends SyncReport {
	readonly enabled: readonly string[];
	readonly alreadyEnabled: boolean;
	readonly platformDependencyAdded: boolean;
	readonly installRan: boolean;
	readonly installed: boolean;
}

export interface DisableReport extends SyncReport {
	readonly enabled: readonly string[];
	readonly alreadyDisabled: boolean;
}

/* Disabling these would detach authentication or the system contract from a
   platform that composes them unconditionally. */
const PROTECTED_MODULES = ['system.core', 'auth.core'] as const;

const GENERATED_FILES = {
	server: 'platform/src/generated/modules.server.ts',
	client: 'platform/src/generated/modules.client.ts',
} as const;

const GENERATED_HEADER =
	'/* GENERATED by "oerp module sync". Do not edit by hand; run\n' +
	'   "pnpm oerp module sync --apply" after enabling or disabling modules. */\n';

function identifier(id: string): string {
	return id.replace(/[^a-zA-Z0-9]+/g, '_');
}

function platformImport(id: string, pkg: string, entry: string): string {
	return `import { ${entry} as ${identifier(id)} } from '${pkg}/platform';`;
}

function clientImport(id: string, pkg: string): string {
	return `import { createClientContribution as ${identifier(id)} } from '${pkg}/client';`;
}

export function generateServerComposition(
	modules: readonly PlatformModuleDescriptor[],
): string {
	const server = modules.filter((module) => module.server);
	const typeImport =
		'import type {\n' +
		'\tPlatformServerComposition,\n' +
		'\tPlatformServerContext,\n' +
		"} from '@coreloom/module-auth/server';\n";
	if (server.length === 0) {
		return (
			GENERATED_HEADER +
			typeImport +
			'\n' +
			'export function composeModuleServer(\n' +
			'\t_context: PlatformServerContext,\n' +
			'): readonly PlatformServerComposition[] {\n' +
			'\treturn [];\n' +
			'}\n'
		);
	}
	const imports = server
		.map((module) =>
			platformImport(module.id, module.package, 'createServerComposition'),
		)
		.join('\n');
	const calls = server
		.map((module) => `\t\t${identifier(module.id)}(context),`)
		.join('\n');
	return (
		GENERATED_HEADER +
		typeImport +
		imports +
		'\n\n' +
		'export function composeModuleServer(\n' +
		'\tcontext: PlatformServerContext,\n' +
		'): readonly PlatformServerComposition[] {\n' +
		'\treturn [\n' +
		calls +
		'\n\t];\n' +
		'}\n'
	);
}

export function generateClientComposition(
	modules: readonly PlatformModuleDescriptor[],
): string {
	const client = modules.filter((module) => module.client);
	const typeImport =
		'import type {\n' +
		'\tModuleClientContext,\n' +
		'\tModuleClientContribution,\n' +
		"} from '@coreloom/client';\n";
	if (client.length === 0) {
		return (
			GENERATED_HEADER +
			typeImport +
			'\n' +
			'export function createModuleClientContributions(\n' +
			'\t_context: ModuleClientContext,\n' +
			'): readonly ModuleClientContribution[] {\n' +
			'\treturn [];\n' +
			'}\n'
		);
	}
	const imports = client
		.map((module) => clientImport(module.id, module.package))
		.join('\n');
	const calls = client
		.map((module) => `\t\t${identifier(module.id)}(context),`)
		.join('\n');
	return (
		GENERATED_HEADER +
		typeImport +
		imports +
		'\n\n' +
		'export function createModuleClientContributions(\n' +
		'\tcontext: ModuleClientContext,\n' +
		'): readonly ModuleClientContribution[] {\n' +
		'\treturn [\n' +
		calls +
		'\n\t];\n' +
		'}\n'
	);
}

async function loadManifests(
	workspace: Workspace,
): Promise<ReadonlyMap<string, PlatformModuleDescriptor>> {
	const files = (await findNamedFiles(workspace.root, 'module.json')).filter(
		(file) => file.includes('/modules/'),
	);
	const descriptors = new Map<string, PlatformModuleDescriptor>();
	for (const file of files) {
		const manifest = JSON.parse(
			await readFile(file, 'utf8'),
		) as PlatformManifest;
		descriptors.set(manifest.id, {
			id: manifest.id,
			package: manifest.package,
			server: manifest.platform?.server === true,
			client: manifest.platform?.client === true,
		});
	}
	return descriptors;
}

function enabledModules(workspace: Workspace): readonly string[] {
	return (
		(workspace.config.modules as { enabled?: string[] } | undefined)?.enabled ??
		[]
	);
}

async function resolveEnabled(
	workspace: Workspace,
	enabled: readonly string[],
): Promise<readonly PlatformModuleDescriptor[]> {
	const manifests = await loadManifests(workspace);
	const missing = enabled.filter((id) => !manifests.has(id));
	if (missing.length > 0) {
		throw new Error(
			`Enabled modules are not registered: ${missing.join(', ')}`,
		);
	}
	return enabled.map((id) => manifests.get(id)!);
}

export async function syncPlatformModules(
	workspace: Workspace,
	apply: boolean,
	enabledOverride?: readonly string[],
): Promise<SyncReport> {
	const enabled = enabledOverride ?? enabledModules(workspace);
	const modules = await resolveEnabled(workspace, enabled);
	const targets = [
		{
			path: GENERATED_FILES.server,
			content: generateServerComposition(modules),
		},
		{
			path: GENERATED_FILES.client,
			content: generateClientComposition(modules),
		},
	];
	const files: SyncedFile[] = [];
	for (const target of targets) {
		const absolute = join(workspace.root, target.path);
		let current = '';
		try {
			current = await readFile(absolute, 'utf8');
		} catch {
			// Missing generated file counts as changed.
		}
		const changed = current !== target.content;
		if (apply && changed) {
			await mkdir(dirname(absolute), { recursive: true });
			await writeFile(absolute, target.content);
		}
		files.push({ path: target.path, changed });
	}
	return {
		modules: modules.map((module) => module.id),
		files,
		applied: apply,
	};
}

export async function enableModule(
	workspace: Workspace,
	id: string,
	apply: boolean,
): Promise<EnableReport> {
	const manifests = await loadManifests(workspace);
	const descriptor = manifests.get(id);
	if (!descriptor) {
		throw new Error(`Unknown module id: ${id}`);
	}
	const current = enabledModules(workspace);
	const alreadyEnabled = current.includes(id);
	const enabled = alreadyEnabled ? current : [...current, id];
	if (apply && !alreadyEnabled) {
		const config = JSON.parse(
			await readFile(workspace.configPath, 'utf8'),
		) as Record<string, unknown>;
		const modules = (config.modules ?? {}) as Record<string, unknown>;
		modules.enabled = enabled;
		config.modules = modules;
		await writeFile(
			workspace.configPath,
			JSON.stringify(config, null, '\t') + '\n',
		);
	}

	// The generated composition imports the module package from platform code,
	// so the platform package.json must declare it and pnpm must link it.
	const platformPackagePath = join(workspace.root, 'platform/package.json');
	const platformPackage = JSON.parse(
		await readFile(platformPackagePath, 'utf8'),
	) as Record<string, unknown> & { dependencies?: Record<string, string> };
	const dependencies = platformPackage.dependencies ?? {};
	const platformDependencyAdded = !(descriptor.package in dependencies);
	if (apply && platformDependencyAdded) {
		dependencies[descriptor.package] = 'workspace:*';
		platformPackage.dependencies = Object.fromEntries(
			Object.entries(dependencies).sort(([left], [right]) =>
				left.localeCompare(right),
			),
		);
		await writeFile(
			platformPackagePath,
			JSON.stringify(platformPackage, null, '\t') + '\n',
		);
	}
	const linked = async () => {
		try {
			await access(
				join(workspace.root, 'platform/node_modules', descriptor.package),
			);
			return true;
		} catch {
			return false;
		}
	};
	let installed = await linked();
	let installRan = false;
	if (apply && !installed) {
		installRan = true;
		const install = spawnSync('pnpm', ['install'], {
			cwd: workspace.root,
			stdio: 'pipe',
			encoding: 'utf8',
		});
		if (install.error || install.status !== 0) {
			const output = `${install.stdout ?? ''}${install.stderr ?? ''}`
				.trim()
				.split('\n')
				.slice(-20)
				.join('\n');
			throw new Error(
				`pnpm install failed while linking the module package${install.error ? ` (${install.error.message})` : ` (exit ${install.status})`}. Run it manually and retry.${output ? `\n${output}` : ''}`,
			);
		}
		installed = await linked();
	}

	const sync = await syncPlatformModules(workspace, apply, enabled);
	return {
		...sync,
		enabled,
		alreadyEnabled,
		platformDependencyAdded,
		installRan,
		installed,
	};
}

export async function disableModule(
	workspace: Workspace,
	id: string,
	apply: boolean,
): Promise<DisableReport> {
	if ((PROTECTED_MODULES as readonly string[]).includes(id)) {
		throw new Error(
			`Module ${id} is part of the platform core and cannot be disabled.`,
		);
	}
	const manifests = await loadManifests(workspace);
	if (!manifests.has(id)) {
		throw new Error(`Unknown module id: ${id}`);
	}
	const current = enabledModules(workspace);
	const alreadyDisabled = !current.includes(id);
	const enabled = current.filter((candidate) => candidate !== id);
	if (apply && !alreadyDisabled) {
		const config = JSON.parse(
			await readFile(workspace.configPath, 'utf8'),
		) as Record<string, unknown>;
		const modules = (config.modules ?? {}) as Record<string, unknown>;
		modules.enabled = enabled;
		config.modules = modules;
		await writeFile(
			workspace.configPath,
			JSON.stringify(config, null, '\t') + '\n',
		);
	}
	const sync = await syncPlatformModules(workspace, apply, enabled);
	return { ...sync, enabled, alreadyDisabled };
}
