import { sdkModules, npmPackage, SDK_VERSION } from './sdk.ts';
import { spawnSync } from 'node:child_process';
import { access, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { ModuleManifest } from '@flowdular/contracts';
import { loadWorkspaceFormatter } from './format.ts';
import { validators } from './validation.ts';
import { findModuleFiles } from './module-files.ts';
import {
	assertModuleCompatibility,
	assertModuleDependency,
} from '@flowdular/kernel';
import type { Workspace } from './workspace.ts';

/* flowdular.json is a workspace file the format gate checks, so write it through
   the workspace Prettier instead of a raw stringify that leaves it unformatted. */
async function writeProjectConfig(
	workspace: Workspace,
	config: Record<string, unknown>,
): Promise<void> {
	const raw = JSON.stringify(config, null, '\t') + '\n';
	const formatter = await loadWorkspaceFormatter(workspace.root);
	const output = formatter
		? await formatter.format(workspace.configPath, raw)
		: raw;
	await writeFile(workspace.configPath, output);
}

export interface PlatformModuleDescriptor {
	readonly id: string;
	readonly package: string;
	readonly server: boolean;
	readonly client: boolean;
	readonly dependencies: readonly string[];
	readonly manifest?: ModuleManifest;
}

interface PlatformManifest extends ModuleManifest {
	readonly platform?: {
		readonly server?: boolean;
		readonly client?: boolean;
	};
}

export interface SyncedFile {
	readonly path: string;
	readonly changed: boolean;
}

export interface SyncReport {
	readonly modules: readonly string[];
	readonly files: readonly SyncedFile[];
	readonly applied: boolean;
}

export interface EnableReport extends SyncReport {
	readonly enabled: readonly string[];
	readonly newlyEnabled: readonly string[];
	readonly alreadyEnabled: boolean;
	readonly platformDependencyAdded: boolean;
	readonly platformDependenciesAdded: readonly string[];
	readonly installRan: boolean;
	readonly installed: boolean;
}

export interface DisableReport extends SyncReport {
	readonly enabled: readonly string[];
	readonly alreadyDisabled: boolean;
}

/* Disabling these would detach authentication or the system contract from a
   platform that composes them unconditionally. */
const PROTECTED_MODULES = ['system.core', 'auth.core'] as const;

const GENERATED_FILES = {
	server: 'platform/src/generated/modules.server.ts',
	client: 'platform/src/generated/modules.client.ts',
} as const;

const GENERATED_HEADER =
	'/* GENERATED by "flowdular module sync". Do not edit by hand; run\n' +
	'   "pnpm flowdular module sync --apply" after enabling or disabling modules. */\n';

function identifier(id: string): string {
	return id.replace(/[^a-zA-Z0-9]+/g, '_');
}

function platformImport(id: string, pkg: string, entry: string): string {
	return `import { ${entry} as ${identifier(id)} } from '${pkg}/platform';`;
}

function clientImport(id: string, pkg: string): string {
	return `import { createClientContribution as ${identifier(id)} } from '${pkg}/client';`;
}

export function generateServerComposition(
	modules: readonly PlatformModuleDescriptor[],
	sdk = false,
	mounts: unknown = [],
	applicationPath = '/app',
): string {
	const server = modules.filter((module) => module.server);
	const typeImport =
		'import type {\n' +
		'\tPlatformServerComposition,\n' +
		'\tPlatformServerContext,\n' +
		`} from '${sdk ? '@flowdular/sdk/modules/auth' : '@flowdular/module-auth'}/server';\n` +
		`import type { WebMount } from '${sdk ? '@flowdular/sdk/server' : '@flowdular/server'}';\n`;
	if (server.length === 0) {
		return (
			GENERATED_HEADER +
			typeImport +
			'\n' +
			'export function composeModuleServer(\n' +
			'\t_context: PlatformServerContext,\n' +
			'): readonly PlatformServerComposition[] {\n' +
			'\treturn [];\n' +
			'}\n' +
			'\nexport const moduleWebMounts: readonly WebMount[] = ' +
			JSON.stringify(mounts) +
			' as const;\n' +
			'export const applicationBasePath = ' +
			JSON.stringify(applicationPath) +
			';\n'
		);
	}
	const imports = server
		.map((module) =>
			platformImport(module.id, module.package, 'createServerComposition'),
		)
		.join('\n');
	const calls = server
		.map(
			(module) =>
				`\t\t{ ...${identifier(module.id)}({\n` +
				`\t\t\t...context,\n` +
				`\t\t\tagentDefinitions: context.agentDefinitions.forModule('${module.id}'),\n` +
				`\t\t}), moduleId: '${module.id}' },`,
		)
		.join('\n');
	return (
		GENERATED_HEADER +
		typeImport +
		imports +
		'\n\n' +
		'export function composeModuleServer(\n' +
		'\tcontext: PlatformServerContext,\n' +
		'): readonly PlatformServerComposition[] {\n' +
		'\treturn [\n' +
		calls +
		'\n\t];\n' +
		'}\n' +
		'\nexport const moduleWebMounts: readonly WebMount[] = ' +
		JSON.stringify(mounts) +
		' as const;\n' +
		'export const applicationBasePath = ' +
		JSON.stringify(applicationPath) +
		';\n'
	);
}

export function generateClientComposition(
	modules: readonly PlatformModuleDescriptor[],
	sdk = false,
	applicationPath = '/app',
): string {
	const client = modules.filter((module) => module.client);
	const typeImport =
		'import type {\n' +
		'\tModuleClientContext,\n' +
		'\tModuleClientContribution,\n' +
		`} from '${sdk ? '@flowdular/sdk/client' : '@flowdular/client'}';\n`;
	if (client.length === 0) {
		return (
			GENERATED_HEADER +
			'export const applicationBasePath = ' +
			JSON.stringify(applicationPath) +
			';\n' +
			typeImport +
			'\n' +
			'export function createModuleClientContributions(\n' +
			'\t_context: ModuleClientContext,\n' +
			'): readonly ModuleClientContribution[] {\n' +
			'\treturn [];\n' +
			'}\n'
		);
	}
	const imports = client
		.map((module) => clientImport(module.id, module.package))
		.join('\n');
	const calls = client
		.map((module) => `\t\t${identifier(module.id)}(context),`)
		.join('\n');
	return (
		GENERATED_HEADER +
		'export const applicationBasePath = ' +
		JSON.stringify(applicationPath) +
		';\n' +
		typeImport +
		imports +
		'\n\n' +
		'export function createModuleClientContributions(\n' +
		'\tcontext: ModuleClientContext,\n' +
		'): readonly ModuleClientContribution[] {\n' +
		'\treturn [\n' +
		calls +
		'\n\t];\n' +
		'}\n'
	);
}

async function loadManifests(
	workspace: Workspace,
): Promise<ReadonlyMap<string, PlatformModuleDescriptor>> {
	const files = await findModuleFiles(workspace);
	const bundled = await sdkModules(workspace);
	const descriptors = new Map<string, PlatformModuleDescriptor>();
	for (const file of files) {
		const manifest = JSON.parse(
			await readFile(file, 'utf8'),
		) as PlatformManifest;
		if (!validators.module(manifest))
			throw new Error(`Invalid module manifest: ${file}`);
		assertModuleCompatibility(manifest);
		if (descriptors.has(manifest.id)) {
			throw new Error(`Module id is registered more than once: ${manifest.id}`);
		}
		descriptors.set(manifest.id, {
			manifest,
			id: manifest.id,
			package: bundled.get(file) ?? manifest.package,
			server: manifest.platform?.server === true,
			client: manifest.platform?.client === true,
			dependencies: manifest.dependencies.map((dependency) => dependency.id),
		});
	}
	return descriptors;
}

function moduleOrder(
	manifests: ReadonlyMap<string, PlatformModuleDescriptor>,
	roots: readonly string[],
	includeDependencies: boolean,
): readonly PlatformModuleDescriptor[] {
	const requested = new Set(roots);
	const visiting: string[] = [];
	const visited = new Set<string>();
	const ordered: PlatformModuleDescriptor[] = [];

	const visit = (id: string, requiredBy?: string): void => {
		if (visited.has(id)) return;
		const cycleStart = visiting.indexOf(id);
		if (cycleStart !== -1) {
			const cycle = [...visiting.slice(cycleStart), id];
			throw new Error(`Dependency cycle detected: ${cycle.join(' -> ')}.`);
		}
		const current = manifests.get(id);
		if (!current) {
			if (requiredBy) {
				throw new Error(
					`Module "${requiredBy}" requires missing module "${id}".`,
				);
			}
			throw new Error(`Enabled module is not registered: ${id}`);
		}

		visiting.push(id);
		for (const dependency of [...current.dependencies].sort((left, right) =>
			left.localeCompare(right),
		)) {
			if (!includeDependencies && !requested.has(dependency)) {
				throw new Error(
					`Enabled module "${id}" requires disabled module "${dependency}". Enable the dependency first.`,
				);
			}
			const constraint = current.manifest?.dependencies.find(
				(entry) => entry.id === dependency,
			);
			const version = manifests.get(dependency)?.manifest?.version;
			if (constraint && version)
				assertModuleDependency(id, constraint, version);
			visit(dependency, id);
		}
		visiting.pop();
		visited.add(id);
		ordered.push(current);
	};

	for (const id of [...requested].sort((left, right) =>
		left.localeCompare(right),
	)) {
		visit(id);
	}
	return ordered;
}

function enabledModules(workspace: Workspace): readonly string[] {
	return (
		(workspace.config.modules as { enabled?: string[] } | undefined)?.enabled ??
		[]
	);
}

async function resolveEnabled(
	workspace: Workspace,
	enabled: readonly string[],
): Promise<readonly PlatformModuleDescriptor[]> {
	const manifests = await loadManifests(workspace);
	return moduleOrder(manifests, enabled, false);
}

function equalIds(left: readonly string[], right: readonly string[]): boolean {
	return (
		left.length === right.length &&
		left.every((value, index) => value === right[index])
	);
}

interface FileSnapshot {
	readonly path: string;
	readonly content: string | undefined;
}

async function takeSnapshots(
	paths: readonly string[],
): Promise<FileSnapshot[]> {
	return Promise.all(
		paths.map(async (path) => {
			try {
				return { path, content: await readFile(path, 'utf8') };
			} catch (error) {
				if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
					return { path, content: undefined };
				}
				throw error;
			}
		}),
	);
}

async function restoreSnapshots(
	snapshots: readonly FileSnapshot[],
): Promise<void> {
	for (const snapshot of [...snapshots].reverse()) {
		if (snapshot.content === undefined) {
			await rm(snapshot.path, { force: true });
			continue;
		}
		await mkdir(dirname(snapshot.path), { recursive: true });
		await writeFile(snapshot.path, snapshot.content);
	}
}

export async function syncPlatformModules(
	workspace: Workspace,
	apply: boolean,
	enabledOverride?: readonly string[],
): Promise<SyncReport> {
	if (
		workspace.config.web !== undefined &&
		!validators.web(workspace.config.web)
	)
		throw new Error('Invalid web mount configuration in flowdular.json.');
	if (
		workspace.config.application !== undefined &&
		!validators.application(workspace.config.application)
	)
		throw new Error('Invalid application path in flowdular.json.');
	const applicationPath =
		(workspace.config.application as { path?: string } | undefined)?.path ??
		'/app';
	const enabled = enabledOverride ?? enabledModules(workspace);
	const sdk = (await sdkModules(workspace)).size > 0;
	const modules = await resolveEnabled(workspace, enabled);
	const formatter = await loadWorkspaceFormatter(workspace.root);
	const targets = await Promise.all(
		[
			{
				path: GENERATED_FILES.server,
				content: generateServerComposition(
					modules,
					sdk,
					(workspace.config.web as { mounts?: unknown } | undefined)?.mounts ??
						[],
					applicationPath,
				),
			},
			{
				path: GENERATED_FILES.client,
				content: generateClientComposition(modules, sdk, applicationPath),
			},
		].map(async (target) => {
			const absolute = join(workspace.root, target.path);
			return {
				...target,
				content: formatter
					? await formatter.format(absolute, target.content)
					: target.content,
			};
		}),
	);
	const files: SyncedFile[] = [];
	for (const target of targets) {
		const absolute = join(workspace.root, target.path);
		let current = '';
		try {
			current = await readFile(absolute, 'utf8');
		} catch {
			// Missing generated file counts as changed.
		}
		const changed = current !== target.content;
		if (apply && changed) {
			await mkdir(dirname(absolute), { recursive: true });
			await writeFile(absolute, target.content);
		}
		files.push({ path: target.path, changed });
	}
	return {
		modules: modules.map((module) => module.id),
		files,
		applied: apply,
	};
}

export async function enableModule(
	workspace: Workspace,
	id: string,
	apply: boolean,
): Promise<EnableReport> {
	const manifests = await loadManifests(workspace);
	const descriptor = manifests.get(id);
	if (!descriptor) {
		throw new Error(`Unknown module id: ${id}`);
	}
	const current = enabledModules(workspace);
	const alreadyEnabled = current.includes(id);
	const modules = moduleOrder(manifests, [...current, id], true);
	const enabled = modules.map((module) => module.id);
	const currentSet = new Set(current);
	const newlyEnabled = enabled.filter((moduleId) => !currentSet.has(moduleId));
	const configChanged = !equalIds(current, enabled);

	// The generated composition imports the module package from platform code,
	// so the platform package.json must declare the full dependency closure and
	// pnpm must link every package before generated code can load.
	const platformPackagePath = join(workspace.root, 'platform/package.json');
	const platformPackage = JSON.parse(
		await readFile(platformPackagePath, 'utf8'),
	) as Record<string, unknown> & { dependencies?: Record<string, string> };
	const dependencies = platformPackage.dependencies ?? {};
	const platformDependenciesAdded = modules
		.map((module) => npmPackage(module.package))
		.filter((packageName) => !(packageName in dependencies))
		.sort((left, right) => left.localeCompare(right));
	const platformDependencyAdded = platformDependenciesAdded.length > 0;
	for (const packageName of platformDependenciesAdded) {
		dependencies[packageName] =
			packageName === '@flowdular/sdk' ? SDK_VERSION : 'workspace:*';
	}
	if (platformDependencyAdded) {
		platformPackage.dependencies = Object.fromEntries(
			Object.entries(dependencies).sort(([left], [right]) =>
				left.localeCompare(right),
			),
		);
	}
	const linked = async (module: PlatformModuleDescriptor) => {
		try {
			await access(
				join(
					workspace.root,
					'platform/node_modules',
					npmPackage(module.package),
				),
			);
			return true;
		} catch {
			return false;
		}
	};
	const allLinked = async () =>
		(await Promise.all(modules.map((module) => linked(module)))).every(Boolean);
	let installed = await allLinked();
	let installRan = false;
	let sync: SyncReport;
	if (apply) {
		const snapshots = await takeSnapshots([
			workspace.configPath,
			join(workspace.root, 'pnpm-lock.yaml'),
			platformPackagePath,
			...Object.values(GENERATED_FILES).map((path) =>
				join(workspace.root, path),
			),
		]);
		try {
			if (configChanged) {
				const config = JSON.parse(
					await readFile(workspace.configPath, 'utf8'),
				) as Record<string, unknown>;
				const configModules = (config.modules ?? {}) as Record<string, unknown>;
				configModules.enabled = enabled;
				config.modules = configModules;
				await writeProjectConfig(workspace, config);
			}
			if (platformDependencyAdded) {
				await writeFile(
					platformPackagePath,
					JSON.stringify(platformPackage, null, '\t') + '\n',
				);
			}
			if (!installed) {
				installRan = true;
				const install = spawnSync(
					'pnpm',
					['install', '--ignore-scripts', '--no-frozen-lockfile'],
					{
						cwd: workspace.root,
						stdio: 'pipe',
						encoding: 'utf8',
					},
				);
				if (install.error || install.status !== 0) {
					const output = `${install.stdout ?? ''}${install.stderr ?? ''}`
						.trim()
						.split('\n')
						.slice(-20)
						.join('\n');
					throw new Error(
						`pnpm install failed while linking the module package${install.error ? ` (${install.error.message})` : ` (exit ${install.status})`}. Run it manually and retry.${output ? `\n${output}` : ''}`,
					);
				}
				installed = await allLinked();
			}
			sync = await syncPlatformModules(workspace, true, enabled);
		} catch (error) {
			await restoreSnapshots(snapshots);
			throw error;
		}
	} else {
		sync = await syncPlatformModules(workspace, false, enabled);
	}

	return {
		...sync,
		enabled,
		newlyEnabled,
		alreadyEnabled,
		platformDependencyAdded,
		platformDependenciesAdded,
		installRan,
		installed,
	};
}

export async function disableModule(
	workspace: Workspace,
	id: string,
	apply: boolean,
): Promise<DisableReport> {
	if ((PROTECTED_MODULES as readonly string[]).includes(id)) {
		throw new Error(
			`Module ${id} is part of the platform core and cannot be disabled.`,
		);
	}
	const manifests = await loadManifests(workspace);
	if (!manifests.has(id)) {
		throw new Error(`Unknown module id: ${id}`);
	}
	const current = enabledModules(workspace);
	const alreadyDisabled = !current.includes(id);
	const orderedCurrent = await resolveEnabled(workspace, current);
	if (!alreadyDisabled) {
		const dependents = new Set([id]);
		for (const module of orderedCurrent) {
			if (
				module.dependencies.some((dependency) => dependents.has(dependency))
			) {
				dependents.add(module.id);
			}
		}
		dependents.delete(id);
		if (dependents.size > 0) {
			throw new Error(
				`Module ${id} is required by enabled module(s): ${[...dependents].sort((left, right) => left.localeCompare(right)).join(', ')}.`,
			);
		}
	}
	const enabled = orderedCurrent
		.filter((module) => module.id !== id)
		.map((module) => module.id);
	const platformPackagePath = join(workspace.root, 'platform/package.json');
	const platformPackage = JSON.parse(
		await readFile(platformPackagePath, 'utf8'),
	) as { dependencies?: Record<string, string> };
	const packageName = npmPackage(manifests.get(id)!.package);
	const dependencyRemoved = Boolean(
		packageName !== '@flowdular/sdk' &&
			platformPackage.dependencies &&
			packageName in platformPackage.dependencies,
	);
	if (dependencyRemoved && platformPackage.dependencies)
		delete platformPackage.dependencies[packageName];
	let sync: SyncReport;
	if (apply && (!alreadyDisabled || dependencyRemoved)) {
		const snapshots = await takeSnapshots([
			workspace.configPath,
			platformPackagePath,
			...Object.values(GENERATED_FILES).map((path) =>
				join(workspace.root, path),
			),
		]);
		try {
			const config = JSON.parse(
				await readFile(workspace.configPath, 'utf8'),
			) as Record<string, unknown>;
			const modules = (config.modules ?? {}) as Record<string, unknown>;
			modules.enabled = enabled;
			config.modules = modules;
			await writeProjectConfig(workspace, config);
			if (dependencyRemoved)
				await writeFile(
					platformPackagePath,
					JSON.stringify(platformPackage, null, '\t') + '\n',
				);
			sync = await syncPlatformModules(workspace, true, enabled);
		} catch (error) {
			await restoreSnapshots(snapshots);
			throw error;
		}
	} else {
		sync = await syncPlatformModules(workspace, apply, enabled);
	}
	return { ...sync, enabled, alreadyDisabled };
}
