import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { AgentRoleDefinition } from './defaults.ts';
import { parseRoleDocument } from './registry.ts';

/* Prettier escapes markdown punctuation in the role documents (ui-\* for
   ui-*). The escape is a rendering detail of the document, not part of the
   instruction a model should read, so it is removed when the document becomes
   the bundled default. */
export function normalizeRoleDocument(
	role: AgentRoleDefinition,
): AgentRoleDefinition {
	return {
		...role,
		instruction: role.instruction.replace(/\\([*_`#[\]])/g, '$1'),
	};
}

export async function loadRoleDocuments(
	directory: string,
): Promise<readonly AgentRoleDefinition[]> {
	const roles: AgentRoleDefinition[] = [];
	for (const entry of (await readdir(directory)).sort()) {
		if (!entry.endsWith('.md')) continue;
		roles.push(
			normalizeRoleDocument(
				parseRoleDocument(await readFile(join(directory, entry), 'utf8')),
			),
		);
	}
	return roles.sort((left, right) => left.id.localeCompare(right.id));
}

function literal(value: string): string {
	return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function template(value: string): string {
	return `\`${value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\``;
}

function list(values: readonly string[]): string {
	return `[${values.map(literal).join(', ')}]`;
}

/* The bundled defaults are generated from the workspace role documents, so
   the two never disagree: the markdown is the source, this module is the
   fallback for a workspace that has not materialized its own copy yet. */
export function renderDefaultsModule(
	roles: readonly AgentRoleDefinition[],
): string {
	const entries = roles.map((role) =>
		[
			'\t{',
			`\t\tid: ${literal(role.id)},`,
			`\t\tname: ${literal(role.name)},`,
			`\t\tpurpose: ${literal(role.purpose)},`,
			`\t\tallowedPaths: ${list(role.allowedPaths)},`,
			`\t\tgates: ${list(role.gates)},`,
			`\t\thandoff: ${list(role.handoff)},`,
			`\t\tinstruction: ${template(role.instruction)},`,
			'\t},',
		].join('\n'),
	);
	return [
		'/* GENERATED from .ai/agents/sandbox/*.md by',
		'   "pnpm --filter @flowdular/coding-agent sync-roles". Edit the markdown',
		'   documents, then regenerate; do not edit this file by hand. */',
		'',
		'export interface AgentRoleDefinition {',
		'\treadonly id: string;',
		'\treadonly name: string;',
		'\treadonly purpose: string;',
		'\t/* Globs relative to the module directory of the session. */',
		'\treadonly allowedPaths: readonly string[];',
		'\treadonly gates: readonly string[];',
		'\treadonly handoff: readonly string[];',
		'\treadonly instruction: string;',
		'}',
		'',
		'/* Specialists with disjoint ownership. The orchestrator routes a turn to',
		'   exactly one of them, so a change always has a single accountable role. */',
		'export const DEFAULT_AGENT_ROLES: readonly AgentRoleDefinition[] = [',
		...entries,
		'];',
		'',
	].join('\n');
}
