import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

/* The platform API a module compiles against is the declaration output of the
   packages every module imports. This script emits those declarations without
   comments, concatenates them in path order and compares the result with the
   committed snapshot. A changed surface without a PLATFORM_API_VERSION bump
   fails `pnpm verify`; a bump regenerates the snapshot with `--update`.

   Version rule while the API stays below 1.0.0: patch for an addition that
   `^0.x.y` consumers still accept, minor for a removal or a changed member.
   Widening a literal union so the old value is still accepted (for example a
   `schemaVersion` of `1` becoming `1 | 2`) counts as an addition. The surface
   covers every package a module source may import: contracts, kernel, server,
   storage, database, harness, cli-protocol, ui, client and the auth composition. */

const root = fileURLToPath(new URL('..', import.meta.url));
const require = createRequire(join(root, 'packages/kernel/package.json'));
const ts = require('typescript');

const SNAPSHOT = 'packages/kernel/platform-api.snapshot.d.ts';
const VERSION_SOURCE = 'packages/contracts/src/index.ts';

/* Entry files modules import, and the source roots whose declarations count as
   the surface. Files outside these roots (node_modules, other packages) are
   type-checked for resolution but not emitted. */
const ENTRIES = [
	'packages/contracts/src/index.ts',
	'packages/kernel/src/index.ts',
	'packages/server/src/index.ts',
	'packages/storage/src/index.ts',
	'packages/database/src/index.ts',
	'packages/harness/src/index.ts',
	'packages/cli-protocol/src/index.ts',
	'packages/ui/src/index.ts',
	'packages/client/src/index.ts',
	'packages/client/src/contributions.ts',
	'packages/client/src/state.ts',
	'modules/auth/src/server/composition.ts',
];
const SURFACE_ROOTS = [
	'packages/contracts/src/',
	'packages/kernel/src/',
	'packages/server/src/',
	'packages/storage/src/',
	'packages/database/src/',
	'packages/harness/src/',
	'packages/cli-protocol/src/',
	'packages/ui/src/',
	'packages/client/src/',
	'packages/client/src/contributions.ts',
	'packages/client/src/state.ts',
	'modules/auth/src/server/composition.ts',
];

async function platformApiVersion() {
	const source = await readFile(join(root, VERSION_SOURCE), 'utf8');
	const match = /export const PLATFORM_API_VERSION = '([^']+)';/.exec(source);
	if (!match)
		throw new Error(`PLATFORM_API_VERSION not found in ${VERSION_SOURCE}.`);
	return match[1];
}

function emitSurface() {
	const options = {
		target: ts.ScriptTarget.ES2022,
		module: ts.ModuleKind.ESNext,
		moduleResolution: ts.ModuleResolutionKind.Bundler,
		allowImportingTsExtensions: true,
		verbatimModuleSyntax: true,
		strict: true,
		skipLibCheck: true,
		declaration: true,
		emitDeclarationOnly: true,
		removeComments: true,
		noEmit: false,
		noEmitOnError: false,
		resolveJsonModule: true,
		allowSyntheticDefaultImports: true,
		esModuleInterop: true,
		exactOptionalPropertyTypes: true,
		noUncheckedIndexedAccess: true,
		lib: ['lib.es2023.d.ts', 'lib.dom.d.ts', 'lib.dom.iterable.d.ts'],
		types: ['node'],
		typeRoots: [join(root, 'packages/kernel/node_modules/@types')],
	};
	const program = ts.createProgram(
		ENTRIES.map((entry) => join(root, entry)),
		options,
	);
	const output = new Map();
	const isSurface = (path) =>
		SURFACE_ROOTS.some((prefix) => path.startsWith(prefix)) &&
		!path.includes('/tests/') &&
		!path.includes('/node_modules/');
	for (const sourceFile of program.getSourceFiles()) {
		const path = relative(root, sourceFile.fileName).split('\\').join('/');
		if (sourceFile.isDeclarationFile || !isSurface(path)) continue;
		const result = program.emit(
			sourceFile,
			(fileName, text) => {
				if (fileName.endsWith('.d.ts')) output.set(path, text);
			},
			undefined,
			true,
		);
		if (result.emitSkipped)
			throw new Error(`Declaration emit skipped for ${path}.`);
		const unresolved = result.diagnostics.filter(
			(entry) => entry.code === 2307,
		);
		if (unresolved.length)
			throw new Error(
				`Unresolved import while emitting ${path}: ${ts.flattenDiagnosticMessageText(unresolved[0].messageText, '\n')}`,
			);
	}
	if (output.size === 0) throw new Error('No surface files were emitted.');
	return [...output.entries()]
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([path, text]) => `// ${path}\n${text.trimEnd()}\n`)
		.join('\n');
}

function render(version, body) {
	return `// platformApi ${version}\n// Generated by scripts/platform-api.mjs; do not edit by hand.\n\n${body}`;
}

function parseSnapshot(text) {
	const match = /^\/\/ platformApi ([^\n]+)\n/.exec(text);
	return match
		? { version: match[1], body: text.slice(text.indexOf('\n\n') + 2) }
		: null;
}

async function main() {
	const update = process.argv.includes('--update');
	const allowSameVersion = process.argv.includes('--allow-same-version');
	const version = await platformApiVersion();
	const body = emitSurface();
	const next = render(version, body);
	let current = null;
	try {
		current = await readFile(join(root, SNAPSHOT), 'utf8');
	} catch (error) {
		if (error.code !== 'ENOENT') throw error;
	}
	if (current === next) {
		console.log(`Platform API ${version} surface matches ${SNAPSHOT}.`);
		return;
	}
	const previous = current ? parseSnapshot(current) : null;
	const sameVersion = previous?.version === version;
	if (!update) {
		if (previous && sameVersion) {
			throw new Error(
				`The platform API surface changed but PLATFORM_API_VERSION is still ${version}. ` +
					`Bump it in ${VERSION_SOURCE} (patch for an addition, minor for a removal or change), then run pnpm platform-api:update.`,
			);
		}
		throw new Error(
			`${SNAPSHOT} is out of date for platform API ${version}. Run pnpm platform-api:update.`,
		);
	}
	if (previous && sameVersion && previous.body !== body && !allowSameVersion) {
		throw new Error(
			`Refusing to rewrite the surface under the same version ${version}. Bump PLATFORM_API_VERSION first, or pass --allow-same-version for a deliberate no-contract change.`,
		);
	}
	await writeFile(join(root, SNAPSHOT), next);
	console.log(`Wrote ${SNAPSHOT} for platform API ${version}.`);
}

await main();
