import {
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { transformSync } from 'esbuild';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import type { ModuleManifest } from '@flowdular/contracts';
import {
	disableModule,
	enableModule,
	generateClientComposition,
	generateServerComposition,
	syncPlatformModules,
	type PlatformModuleDescriptor,
} from '../src/module-sync.ts';
import type { Workspace } from '../src/workspace.ts';

const modules: readonly PlatformModuleDescriptor[] = [
	{
		id: 'users.core',
		package: '@flowdular/module-users',
		server: true,
		client: true,
		dependencies: [],
	},
	{
		id: 'billing.core',
		package: '@flowdular/module-billing',
		server: true,
		client: false,
		dependencies: [],
	},
];

const workspaces: string[] = [];

afterEach(() => {
	for (const workspace of workspaces.splice(0)) {
		rmSync(workspace, { recursive: true, force: true });
	}
});

function manifest(
	id: string,
	dependencies: readonly string[] = [],
): ModuleManifest & {
	readonly platform: { readonly server: true; readonly client: true };
} {
	return {
		schemaVersion: 1,
		id,
		package: `@flowdular/module-${id.split('.')[0]}`,
		version: '1.0.0',
		profile: 'full',
		capabilities: ['api', 'client'],
		dependencies: dependencies.map((dependency) => ({
			id: dependency,
			range: '^1.0.0',
		})),
		tenancy: 'required',
		locales: ['en'],
		stability: 'experimental',
		platform: { server: true, client: true },
	};
}

function createWorkspace(
	manifests: readonly ModuleManifest[],
	enabled: readonly string[],
): Workspace {
	const root = mkdtempSync(join(tmpdir(), 'flowdular-module-sync-'));
	workspaces.push(root);
	const configPath = join(root, 'flowdular.json');
	const config = { modules: { enabled: [...enabled] } };
	writeFileSync(configPath, JSON.stringify(config, null, 2));
	mkdirSync(join(root, 'platform/node_modules'), { recursive: true });
	writeFileSync(
		join(root, 'platform/package.json'),
		JSON.stringify({ name: '@test/platform', dependencies: {} }, null, 2),
	);
	for (const [index, entry] of manifests.entries()) {
		const directory = join(root, 'modules', `${index}-${entry.id}`);
		mkdirSync(directory, { recursive: true });
		writeFileSync(
			join(directory, 'module.json'),
			JSON.stringify(entry, null, 2),
		);
		mkdirSync(join(root, 'platform/node_modules', entry.package), {
			recursive: true,
		});
	}
	return { root, configPath, config };
}

describe('platform composition generator', () => {
	it('emits the same configurable application path for the server and client', () => {
		expect(
			generateServerComposition(modules, false, [], '/backoffice'),
		).toContain('export const applicationBasePath = "/backoffice";');
		expect(generateClientComposition(modules, false, '/backoffice')).toContain(
			'export const applicationBasePath = "/backoffice";',
		);
	});
	it('binds module ownership after its returned composition and includes operator mount configuration', () => {
		const source = generateServerComposition(modules, false, [
			{
				id: 'site',
				moduleId: 'users.core',
				surfaceId: 'portal',
				tenantId: 'tenant-a',
				path: '/sites/a',
			},
		]);
		expect(source).toContain("}), moduleId: 'users.core' }");
		expect(source).toContain(
			'export const moduleWebMounts: readonly WebMount[] =',
		);
		expect(source).toContain('"tenantId":"tenant-a"');
	});
	it('wires server compositions for enabled modules in order', () => {
		const source = generateServerComposition(modules);
		expect(source).toContain('GENERATED by "flowdular module sync"');
		expect(source).toContain(
			"import { createServerComposition as users_core } from '@flowdular/module-users/platform';",
		);
		expect(source.indexOf('users_core({')).toBeLessThan(
			source.indexOf('billing_core({'),
		);
		expect(source).toContain(
			"agentDefinitions: context.agentDefinitions.forModule('users.core')",
		);
	});

	it('scopes the capability registry to the manifest declaration', () => {
		const declared = manifest('agents.core');
		const source = generateServerComposition([
			{
				id: 'agents.core',
				package: '@flowdular/module-agents',
				server: true,
				client: false,
				dependencies: [],
				manifest: {
					...declared,
					provides: ['agents.run-queue'],
					requires: [{ id: 'notifications.publish.v1', optional: true }],
				},
			},
		]);
		expect(source).toContain(
			`capabilities: context.capabilities.forModule('agents.core', {"provides":["agents.run-queue"],"requires":[{"id":"notifications.publish.v1","optional":true}]})`,
		);
		expect(generateServerComposition(modules)).not.toContain(
			'capabilities: context.capabilities.forModule',
		);
	});

	it('binds the metrics of each module and hands every module the same tracer', () => {
		const source = generateServerComposition(modules);
		expect(source).toContain(
			"import { createModuleMetrics } from '@flowdular/server';",
		);
		expect(source).toContain("metrics: createModuleMetrics('users.core'),");
		expect(source).toContain("metrics: createModuleMetrics('billing.core'),");
		/* The tracer is the platform's, not a per-module binding, so it reaches a
		   module through the context the call spreads. */
		expect(source).toContain('...context,');
		expect(generateServerComposition(modules, true)).toContain(
			"import { createModuleMetrics } from '@flowdular/sdk/server';",
		);
	});

	it('wires client contributions only for client-capable modules', () => {
		const source = generateClientComposition(modules);
		expect(source).toContain('users_core(context)');
		expect(source).not.toContain('billing_core');
	});

	it('emits empty compositions without imports', () => {
		expect(generateServerComposition([])).toContain('return [];');
		expect(generateClientComposition([])).toContain('return [];');
		expect(generateServerComposition([])).not.toContain('/platform');
		expect(generateServerComposition([])).not.toContain('createModuleMetrics');
	});
});

describe('module dependency lifecycle', () => {
	it('enables the complete dependency closure in deterministic topological order', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['support.core', 'auth.core']),
				manifest('support.core', ['system.core']),
				manifest('system.core'),
				manifest('auth.core', ['system.core']),
			],
			[],
		);

		const report = await enableModule(workspace, 'feature.core', false);

		expect(report.enabled).toEqual([
			'system.core',
			'auth.core',
			'support.core',
			'feature.core',
		]);
		expect(report.newlyEnabled).toEqual(report.enabled);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual([]);
	});

	it('writes the closure and composes dependencies before consumers on apply', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['auth.core']),
				manifest('auth.core', ['system.core']),
				manifest('system.core'),
			],
			[],
		);

		const report = await enableModule(workspace, 'feature.core', true);
		const config = JSON.parse(readFileSync(workspace.configPath, 'utf8')) as {
			modules: { enabled: string[] };
		};
		const source = readFileSync(
			join(workspace.root, 'platform/src/generated/modules.server.ts'),
			'utf8',
		);

		expect(config.modules.enabled).toEqual([
			'system.core',
			'auth.core',
			'feature.core',
		]);
		expect(report.modules).toEqual(config.modules.enabled);
		expect(source.indexOf('system_core({')).toBeLessThan(
			source.indexOf('auth_core({'),
		);
		expect(source.indexOf('auth_core({')).toBeLessThan(
			source.indexOf('feature_core({'),
		);
	});

	it('orders a required capability provider before its consumer and refuses a disabled provider', async () => {
		const provider = {
			...manifest('agents.core'),
			provides: ['agents.run-queue'],
		};
		const consumer = {
			...manifest('automations.core'),
			requires: [
				{ id: 'agents.run-queue' },
				{ id: 'workflows.execution.v1', optional: true },
			],
		};
		const enabled = createWorkspace([consumer, provider], ['automations.core']);
		await expect(syncPlatformModules(enabled, false)).rejects.toThrow(
			'Enabled module "automations.core" requires capability "agents.run-queue" from disabled module "agents.core". Enable the provider first.',
		);
		const closure = createWorkspace([consumer, provider], []);
		const report = await enableModule(closure, 'automations.core', false);
		expect(report.modules).toEqual(['agents.core', 'automations.core']);
		const orphan = createWorkspace([consumer], []);
		await expect(
			enableModule(orphan, 'automations.core', false),
		).rejects.toThrow(
			'Module "automations.core" requires capability "agents.run-queue" and no module provides it.',
		);
	});

	it('sorts an existing enabled set topologically instead of trusting config order', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['auth.core']),
				manifest('system.core'),
				manifest('auth.core', ['system.core']),
			],
			['feature.core', 'auth.core', 'system.core'],
		);

		const report = await syncPlatformModules(workspace, false);

		expect(report.modules).toEqual([
			'system.core',
			'auth.core',
			'feature.core',
		]);
	});

	it('formats generated compositions before comparing or writing them', async () => {
		const integration = {
			...manifest('automations-workflows.integration'),
			package: '@flowdular/module-automations-workflows-integration',
		};
		const workspace = createWorkspace(
			[integration],
			['automations-workflows.integration'],
		);

		await syncPlatformModules(workspace, true);
		const source = readFileSync(
			join(workspace.root, 'platform/src/generated/modules.server.ts'),
			'utf8',
		);

		expect(() => transformSync(source, { loader: 'ts' })).not.toThrow();
		expect(source).not.toBe(
			generateServerComposition([
				{
					id: integration.id,
					package: integration.package,
					server: true,
					client: true,
					dependencies: [],
				},
			]),
		);
		expect(source).toContain(
			"agentDefinitions: context.agentDefinitions.forModule(\n\t\t\t\t\t'automations-workflows.integration',\n\t\t\t\t)",
		);
	});

	it('refuses to disable a module required by an enabled dependent', async () => {
		const workspace = createWorkspace(
			[
				manifest('application.core', ['feature.core']),
				manifest('feature.core', ['support.core']),
				manifest('support.core'),
			],
			['application.core', 'support.core', 'feature.core'],
		);

		await expect(
			disableModule(workspace, 'support.core', true),
		).rejects.toThrowError(
			'Module support.core is required by enabled module(s): application.core, feature.core.',
		);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual(['application.core', 'support.core', 'feature.core']);
	});

	it('refuses a missing dependency without changing the workspace', async () => {
		const workspace = createWorkspace(
			[manifest('feature.core', ['missing.core'])],
			[],
		);

		await expect(
			enableModule(workspace, 'feature.core', true),
		).rejects.toThrowError(
			'Module "feature.core" requires missing module "missing.core".',
		);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual([]);
	});

	it('refuses dependency cycles without changing the workspace', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['support.core']),
				manifest('support.core', ['feature.core']),
			],
			[],
		);

		await expect(
			enableModule(workspace, 'feature.core', true),
		).rejects.toThrowError(
			'Dependency cycle detected: feature.core -> support.core -> feature.core.',
		);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual([]);
	});

	it('restores config and platform dependencies when package linking fails', async () => {
		const entry = manifest('feature.core');
		const workspace = createWorkspace([entry], []);
		rmSync(join(workspace.root, 'platform/node_modules', entry.package), {
			recursive: true,
			force: true,
		});
		const configBefore = readFileSync(workspace.configPath, 'utf8');
		const packageBefore = readFileSync(
			join(workspace.root, 'platform/package.json'),
			'utf8',
		);
		const path = process.env.PATH;
		process.env.PATH = '';
		try {
			await expect(
				enableModule(workspace, 'feature.core', true),
			).rejects.toThrowError('pnpm install failed while linking');
		} finally {
			if (path === undefined) delete process.env.PATH;
			else process.env.PATH = path;
		}

		expect(readFileSync(workspace.configPath, 'utf8')).toBe(configBefore);
		expect(
			readFileSync(join(workspace.root, 'platform/package.json'), 'utf8'),
		).toBe(packageBefore);
	});
});

it('removes the disabled module package while retaining other platform dependencies', async () => {
	const workspace = createWorkspace(
		[manifest('auth.core'), manifest('billing.core')],
		['auth.core', 'billing.core'],
	);
	const path = join(workspace.root, 'platform/package.json');
	writeFileSync(
		path,
		JSON.stringify({
			name: '@test/platform',
			dependencies: {
				'@flowdular/module-auth': 'workspace:*',
				'@flowdular/module-billing': 'workspace:*',
				unrelated: '1.0.0',
			},
		}),
	);
	await disableModule(workspace, 'billing.core', true);
	expect(JSON.parse(readFileSync(path, 'utf8')).dependencies).toEqual({
		'@flowdular/module-auth': 'workspace:*',
		unrelated: '1.0.0',
	});
});
it('refuses incompatible dependency versions before generating composition', async () => {
	const consumer = {
		...manifest('billing.core'),
		dependencies: [{ id: 'auth.core', range: '^0.1.0' }],
	};
	const workspace = createWorkspace(
		[manifest('auth.core'), consumer],
		['auth.core'],
	);
	await expect(enableModule(workspace, 'billing.core', true)).rejects.toThrow(
		/requires auth.core \^0.1.0; available 1.0.0/,
	);
	expect(
		JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
	).toEqual(['auth.core']);
});

it('discovers SDK modules, composes SDK exports and retains the shared dependency on disable', async () => {
	const workspace = createWorkspace([], ['auth.core', 'users.core']);
	const sdk = join(workspace.root, 'platform/node_modules/@flowdular/sdk');
	mkdirSync(sdk, { recursive: true });
	writeFileSync(
		join(sdk, 'package.json'),
		JSON.stringify({
			name: '@flowdular/sdk',
			version: '0.2.0',
			exports: { './modules.json': './modules.json' },
		}),
	);
	writeFileSync(
		join(workspace.root, 'platform/package.json'),
		JSON.stringify({ dependencies: { '@flowdular/sdk': '0.2.0' } }),
	);
	for (const name of ['auth', 'users']) {
		mkdirSync(join(sdk, 'modules', name), { recursive: true });
		writeFileSync(
			join(sdk, 'modules', name, 'module.json'),
			JSON.stringify(
				manifest(name + '.core', name === 'users' ? ['auth.core'] : []),
			),
		);
	}
	writeFileSync(
		join(sdk, 'modules.json'),
		JSON.stringify({
			schemaVersion: 1,
			modules: ['auth', 'users'].map((name) => ({
				manifest: `modules/${name}/module.json`,
				import: `@flowdular/sdk/modules/${name}`,
			})),
		}),
	);
	await syncPlatformModules(workspace, true);
	expect(
		readFileSync(
			join(workspace.root, 'platform/src/generated/modules.server.ts'),
			'utf8',
		),
	).toContain("from '@flowdular/sdk/modules/users/platform'");
	expect(
		readFileSync(
			join(workspace.root, 'platform/src/generated/modules.client.ts'),
			'utf8',
		),
	).toContain("from '@flowdular/sdk/client'");
	await disableModule(workspace, 'users.core', true);
	expect(
		JSON.parse(
			readFileSync(join(workspace.root, 'platform/package.json'), 'utf8'),
		).dependencies,
	).toEqual({ '@flowdular/sdk': '0.2.0' });
	expect(
		readFileSync(
			join(workspace.root, 'platform/src/generated/modules.server.ts'),
			'utf8',
		),
	).not.toContain('modules/users/platform');
});
