import {
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import type { ModuleManifest } from '@coreloom/contracts';
import {
	disableModule,
	enableModule,
	generateClientComposition,
	generateServerComposition,
	syncPlatformModules,
	type PlatformModuleDescriptor,
} from '../src/module-sync.ts';
import type { Workspace } from '../src/workspace.ts';

const modules: readonly PlatformModuleDescriptor[] = [
	{
		id: 'users.core',
		package: '@coreloom/module-users',
		server: true,
		client: true,
		dependencies: [],
	},
	{
		id: 'billing.core',
		package: '@coreloom/module-billing',
		server: true,
		client: false,
		dependencies: [],
	},
];

const workspaces: string[] = [];

afterEach(() => {
	for (const workspace of workspaces.splice(0)) {
		rmSync(workspace, { recursive: true, force: true });
	}
});

function manifest(
	id: string,
	dependencies: readonly string[] = [],
): ModuleManifest & {
	readonly platform: { readonly server: true; readonly client: true };
} {
	return {
		schemaVersion: 1,
		id,
		package: `@coreloom/module-${id.split('.')[0]}`,
		version: '1.0.0',
		profile: 'full',
		capabilities: ['api', 'client'],
		dependencies: dependencies.map((dependency) => ({
			id: dependency,
			range: '^1.0.0',
		})),
		tenancy: 'required',
		locales: ['en'],
		stability: 'experimental',
		platform: { server: true, client: true },
	};
}

function createWorkspace(
	manifests: readonly ModuleManifest[],
	enabled: readonly string[],
): Workspace {
	const root = mkdtempSync(join(tmpdir(), 'coreloom-module-sync-'));
	workspaces.push(root);
	const configPath = join(root, 'coreloom.json');
	const config = { modules: { enabled: [...enabled] } };
	writeFileSync(configPath, JSON.stringify(config, null, 2));
	mkdirSync(join(root, 'platform/node_modules'), { recursive: true });
	writeFileSync(
		join(root, 'platform/package.json'),
		JSON.stringify({ name: '@test/platform', dependencies: {} }, null, 2),
	);
	for (const [index, entry] of manifests.entries()) {
		const directory = join(root, 'modules', `${index}-${entry.id}`);
		mkdirSync(directory, { recursive: true });
		writeFileSync(
			join(directory, 'module.json'),
			JSON.stringify(entry, null, 2),
		);
		mkdirSync(join(root, 'platform/node_modules', entry.package), {
			recursive: true,
		});
	}
	return { root, configPath, config };
}

describe('platform composition generator', () => {
	it('wires server compositions for enabled modules in order', () => {
		const source = generateServerComposition(modules);
		expect(source).toContain('GENERATED by "coreloom module sync"');
		expect(source).toContain(
			"import { createServerComposition as users_core } from '@coreloom/module-users/platform';",
		);
		expect(source.indexOf('users_core({')).toBeLessThan(
			source.indexOf('billing_core({'),
		);
		expect(source).toContain(
			"agentDefinitions: context.agentDefinitions.forModule('users.core')",
		);
	});

	it('wires client contributions only for client-capable modules', () => {
		const source = generateClientComposition(modules);
		expect(source).toContain('users_core(context)');
		expect(source).not.toContain('billing_core');
	});

	it('emits empty compositions without imports', () => {
		expect(generateServerComposition([])).toContain('return [];');
		expect(generateClientComposition([])).toContain('return [];');
		expect(generateServerComposition([])).not.toContain('/platform');
	});
});

describe('module dependency lifecycle', () => {
	it('enables the complete dependency closure in deterministic topological order', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['support.core', 'auth.core']),
				manifest('support.core', ['system.core']),
				manifest('system.core'),
				manifest('auth.core', ['system.core']),
			],
			[],
		);

		const report = await enableModule(workspace, 'feature.core', false);

		expect(report.enabled).toEqual([
			'system.core',
			'auth.core',
			'support.core',
			'feature.core',
		]);
		expect(report.newlyEnabled).toEqual(report.enabled);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual([]);
	});

	it('writes the closure and composes dependencies before consumers on apply', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['auth.core']),
				manifest('auth.core', ['system.core']),
				manifest('system.core'),
			],
			[],
		);

		const report = await enableModule(workspace, 'feature.core', true);
		const config = JSON.parse(readFileSync(workspace.configPath, 'utf8')) as {
			modules: { enabled: string[] };
		};
		const source = readFileSync(
			join(workspace.root, 'platform/src/generated/modules.server.ts'),
			'utf8',
		);

		expect(config.modules.enabled).toEqual([
			'system.core',
			'auth.core',
			'feature.core',
		]);
		expect(report.modules).toEqual(config.modules.enabled);
		expect(source.indexOf('system_core({')).toBeLessThan(
			source.indexOf('auth_core({'),
		);
		expect(source.indexOf('auth_core({')).toBeLessThan(
			source.indexOf('feature_core({'),
		);
	});

	it('sorts an existing enabled set topologically instead of trusting config order', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['auth.core']),
				manifest('system.core'),
				manifest('auth.core', ['system.core']),
			],
			['feature.core', 'auth.core', 'system.core'],
		);

		const report = await syncPlatformModules(workspace, false);

		expect(report.modules).toEqual([
			'system.core',
			'auth.core',
			'feature.core',
		]);
	});

	it('formats generated compositions before comparing or writing them', async () => {
		const integration = {
			...manifest('automations-workflows.integration'),
			package: '@coreloom/module-automations-workflows-integration',
		};
		const workspace = createWorkspace(
			[integration],
			['automations-workflows.integration'],
		);

		await syncPlatformModules(workspace, true);
		const source = readFileSync(
			join(workspace.root, 'platform/src/generated/modules.server.ts'),
			'utf8',
		);

		expect(source).not.toBe(
			generateServerComposition([
				{
					id: integration.id,
					package: integration.package,
					server: true,
					client: true,
					dependencies: [],
				},
			]),
		);
		expect(source).toContain(
			"agentDefinitions: context.agentDefinitions.forModule(\n\t\t\t\t'automations-workflows.integration',\n\t\t\t)",
		);
	});

	it('refuses to disable a module required by an enabled dependent', async () => {
		const workspace = createWorkspace(
			[
				manifest('application.core', ['feature.core']),
				manifest('feature.core', ['support.core']),
				manifest('support.core'),
			],
			['application.core', 'support.core', 'feature.core'],
		);

		await expect(
			disableModule(workspace, 'support.core', true),
		).rejects.toThrowError(
			'Module support.core is required by enabled module(s): application.core, feature.core.',
		);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual(['application.core', 'support.core', 'feature.core']);
	});

	it('refuses a missing dependency without changing the workspace', async () => {
		const workspace = createWorkspace(
			[manifest('feature.core', ['missing.core'])],
			[],
		);

		await expect(
			enableModule(workspace, 'feature.core', true),
		).rejects.toThrowError(
			'Module "feature.core" requires missing module "missing.core".',
		);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual([]);
	});

	it('refuses dependency cycles without changing the workspace', async () => {
		const workspace = createWorkspace(
			[
				manifest('feature.core', ['support.core']),
				manifest('support.core', ['feature.core']),
			],
			[],
		);

		await expect(
			enableModule(workspace, 'feature.core', true),
		).rejects.toThrowError(
			'Dependency cycle detected: feature.core -> support.core -> feature.core.',
		);
		expect(
			JSON.parse(readFileSync(workspace.configPath, 'utf8')).modules.enabled,
		).toEqual([]);
	});

	it('restores config and platform dependencies when package linking fails', async () => {
		const entry = manifest('feature.core');
		const workspace = createWorkspace([entry], []);
		rmSync(join(workspace.root, 'platform/node_modules', entry.package), {
			recursive: true,
			force: true,
		});
		const configBefore = readFileSync(workspace.configPath, 'utf8');
		const packageBefore = readFileSync(
			join(workspace.root, 'platform/package.json'),
			'utf8',
		);
		const path = process.env.PATH;
		process.env.PATH = '';
		try {
			await expect(
				enableModule(workspace, 'feature.core', true),
			).rejects.toThrowError('pnpm install failed while linking');
		} finally {
			if (path === undefined) delete process.env.PATH;
			else process.env.PATH = path;
		}

		expect(readFileSync(workspace.configPath, 'utf8')).toBe(configBefore);
		expect(
			readFileSync(join(workspace.root, 'platform/package.json'), 'utf8'),
		).toBe(packageBefore);
	});
});
