import { describe, expect, it } from 'vitest';
import {
	generateClientComposition,
	generateServerComposition,
	type PlatformModuleDescriptor,
} from '../src/module-sync.ts';

const modules: readonly PlatformModuleDescriptor[] = [
	{
		id: 'users.core',
		package: '@coreloom/module-users',
		server: true,
		client: true,
	},
	{
		id: 'billing.core',
		package: '@coreloom/module-billing',
		server: true,
		client: false,
	},
];

describe('platform composition generator', () => {
	it('wires server compositions for enabled modules in order', () => {
		const source = generateServerComposition(modules);
		expect(source).toContain('GENERATED by "oerp module sync"');
		expect(source).toContain(
			"import { createServerComposition as users_core } from '@coreloom/module-users/platform';",
		);
		expect(source.indexOf('users_core(context)')).toBeLessThan(
			source.indexOf('billing_core(context)'),
		);
	});

	it('wires client contributions only for client-capable modules', () => {
		const source = generateClientComposition(modules);
		expect(source).toContain('users_core(context)');
		expect(source).not.toContain('billing_core');
	});

	it('emits empty compositions without imports', () => {
		expect(generateServerComposition([])).toContain('return [];');
		expect(generateClientComposition([])).toContain('return [];');
		expect(generateServerComposition([])).not.toContain('/platform');
	});
});
